#!/usr/bin/env bun
/**
 * Build `styles.css` from `src/ui/tailwind.css`.
 *
 * The result is committed: `dist/` is gitignored repo-wide, and a workspace
 * consumer imports this package from source, so a stylesheet that only existed
 * after a build step would be missing exactly when it is needed. A test
 * rebuilds it and fails when the committed copy is stale.
 */
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const BANNER = '/* generated by bun run build:css — do not edit */\n';

/** Build the stylesheet and return it, without writing anything. */
export async function buildCss(): Promise<string> {
  const out = join(root, '.broapp-css.tmp');
  const built = Bun.spawn(
    ['bunx', '@tailwindcss/cli', '-i', 'src/ui/tailwind.css', '-o', out, '--minify'],
    { cwd: root, stdout: 'pipe', stderr: 'pipe' },
  );
  if ((await built.exited) !== 0) {
    throw new Error(`building the stylesheet failed:\n${await new Response(built.stderr).text()}`);
  }
  const css = await Bun.file(out).text();
  await Bun.file(out).delete();
  // Tailwind's own banner carries its homepage URL. A test asserts the
  // stylesheet holds no absolute address at all — the rule that keeps a page
  // from loading anything off-origin is easier to defend when it has no
  // exceptions — so the banner goes and ours takes its place.
  return BANNER + css.replace(/\/\*![\s\S]*?\*\//g, '');
}

if (import.meta.main) {
  await Bun.write(join(root, 'styles.css'), await buildCss());
  console.log('wrote styles.css');
}
